QLKhachSan/QLKhachSan/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.RoomReservationDetails = new HashSet<RoomReservationDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CMND { get; set; }
        public string Add { get; set; }
        public int CustomerTypeId { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationDetail> RoomReservationDetails { get; set; }
    }
}

QLKhachSan/QLKhachSan/Models/CustomerType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

QLKhachSan/QLKhachSan/Controllers/CustomerTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKhachSan.Models;

namespace QLKhachSan.Controllers
{
    public class CustomerTypesController : Controller
    {
        private NOBLESSEDatabase db = new NOBLESSEDatabase();

        // GET: CustomerTypes
        public ActionResult Index()
        {
            return View(db.CustomerTypes.ToList());
        }

        // GET: CustomerTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerType customerType = db.CustomerTypes.Find(id);
            if (customerType == null)
            {
                return HttpNotFound();
            }
            return View(customerType);
        }

        // GET: CustomerTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] CustomerType customerType)
        {
            if (ModelState.IsValid)
            {
                db.CustomerTypes.Add(customerType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customerType);
        }

        // GET: CustomerTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerType customerType = db.CustomerTypes.Find(id);
            if (customerType == null)
            {
                return HttpNotFound();
            }
            return View(customerType);
        }

        // POST: CustomerTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] CustomerType customerType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customerType);
        }

        // GET: CustomerTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerType customerType = db.CustomerTypes.Find(id);
            if (customerType == null)
            {
                return HttpNotFound();
            }
            return View(customerType);
        }

        // POST: CustomerTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerType customerType = db.CustomerTypes.Find(id);
            db.CustomerTypes.Remove(customerType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKhachSan/QLKhachSan/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKhachSan.Models;

namespace QLKhachSan.Controllers
{
    public class CustomersController : Controller
    {
        private NOBLESSEDatabase db = new NOBLESSEDatabase();
        public int m_roomReservationId;
        // GET: Customers

        public ActionResult AddToReservation(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var customers = db.Customers.Include(c => c.CustomerType);
            ViewBag.RoomReservationId = id;
            return View(customers.ToList());
        }


        public ActionResult Index()
        {
            var customers = db.Customers.Include(c => c.CustomerType);
            return View(customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create(int id)
        {
            var roomReservation = db.RoomReservations.Find(id);
            if (roomReservation == null)
                return HttpNotFound();

            ViewBag.RoomReservationId = id;
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "Name");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();

                var roomReservationDetail = new RoomReservationDetail();
                roomReservationDetail.CustomerId = customer.Id;
                roomReservationDetail.RoomReservationId = id;
                db.RoomReservationDetails.Add(roomReservationDetail);
                db.SaveChanges();

                return RedirectToAction("Details", "RoomReservations", new { id = id });
            }

            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "Name", customer.CustomerTypeId);
            return View(customer);
        }

        public ActionResult MoveOutReservation(int reservation, int details)
        {
            var roomDetail = db.RoomReservationDetails.Find(details);
            db.RoomReservationDetails.Remove(roomDetail);
            db.SaveChanges();

            return RedirectToAction("Details", "RoomReservations", new { id = reservation });
        }

        public ActionResult Add(int reservation, int id)
        {
            var customer = db.Customers.Find(id);

            if (customer == null)
                return HttpNotFound();

            var roomReservationDetail = new RoomReservationDetail();
            roomReservationDetail.CustomerId = customer.Id;
            roomReservationDetail.RoomReservationId = reservation;

            db.RoomReservationDetails.Add(roomReservationDetail);
            db.SaveChanges();

            return RedirectToAction("Details", "RoomReservations", new { id = reservation });
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "Name", customer.CustomerTypeId);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CMND,Add,CustomerTypeId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "Name", customer.CustomerTypeId);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKhachSan/QLKhachSan/Controllers/RoomReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKhachSan.Models;

namespace QLKhachSan.Controllers
{
    public class RoomReservationsController : Controller
    {
        private NOBLESSEDatabase db = new NOBLESSEDatabase();

        public ActionResult Bill(int id)
        {
            var roomReservations = db.RoomReservations.Where(r => r.DateEnded == null);
            ViewBag.BillId = id;
            return View(roomReservations.ToList());
        }

        public ActionResult AddToBill(int id, int reservation)
        {
            var billObj = db.Bills.FirstOrDefault(p => p.Id == id);
            var resObj = db.RoomReservations.FirstOrDefault(p => p.Id == reservation);

            if (billObj == null || resObj == null)
                return HttpNotFound();

            resObj.BillId = id;
            db.Entry(resObj).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Details", "Bills", new { id = id });
        }

        // GET: RoomReservations
        public ActionResult Index()
        {
            return View(db.RoomReservations.ToList());
        }

        // GET: RoomReservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomReservation roomReservation = db.RoomReservations.Find(id);
            if (roomReservation == null)
            {
                return HttpNotFound();
            }
            return View(roomReservation);
        }

        // GET: RoomReservations/Create
        public ActionResult Create(int? id)
        {
            if (id == null || db.Rooms.Find(id) == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = id.ToString();
            return View();
        }

        // POST: RoomReservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomReservation roomReservation)
        {
            //if (ModelState.IsValid)
            //{
                roomReservation.DateCreated = DateTime.Today;
                db.RoomReservations.Add(roomReservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            //}

            ViewBag.RoomId = new SelectList(db.Rooms, "Id", "Name", roomReservation.RoomId);
            return View(roomReservation);
        }

        // GET: RoomReservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomReservation roomReservation = db.RoomReservations.Find(id);
            if (roomReservation == null)
            {
                return HttpNotFound();
            }
            return View(roomReservation);
        }

        // POST: RoomReservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateCreated,DateEnded")] RoomReservation roomReservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomReservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roomReservation);
        }

        // GET: RoomReservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomReservation roomReservation = db.RoomReservations.Find(id);
            if (roomReservation == null)
            {
                return HttpNotFound();
            }
            return View(roomReservation);
        }

        // POST: RoomReservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoomReservation roomReservation = db.RoomReservations.Find(id);
            db.RoomReservations.Remove(roomReservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKhachSan/QLKhachSan/Views/Customers/AddToReservation.cshtml
@model IEnumerable<QLKhachSan.Models.Customer>

@{
    ViewBag.Title = "Index";
}

<h2>Customers</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = @ViewBag.RoomReservationId }, new { @class = "btn-custom btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Add)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerType.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Add)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerType.Name)
            </td>
            <td>
                @{
                    ViewBag.Add = true ;
                }
                @foreach (var resDetail in item.RoomReservationDetails)
                {
                    if (resDetail.RoomReservationId == @ViewBag.RoomReservationId)
                    {
                        ViewBag.Add = false;
                        break;
                    }
                }
                @if (@ViewBag.Add == true)
                {
                    @Html.ActionLink("Add", "Add", null, new { reservation = @ViewBag.RoomReservationId, id = item.Id }, new { @class = "btn-custom btn btn-primary" })

                }
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to List", "Details", "RoomReservations", new { id = @ViewBag.RoomReservationId }, null)
</div>

QLKhachSan/QLKhachSan/Views/Customers/Create.cshtml
@model QLKhachSan.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Add, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Add, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Add, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerTypeId, "Customer Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerTypeId, "", new { @class = "text-danger" })
                @Html.ActionLink("Add new", "Create", "CustomerTypes", null, new { @class = "btn-custom btn btn-success" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKhachSan/QLKhachSan/Views/Customers/Delete.cshtml
@model QLKhachSan.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Add)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Add)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerType.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QLKhachSan/QLKhachSan/Views/Customers/Details.cshtml
@model QLKhachSan.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Add)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Add)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerType.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLKhachSan/QLKhachSan/Views/Customers/Edit.cshtml
@model QLKhachSan.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Add, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Add, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Add, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerTypeId, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKhachSan/QLKhachSan/Views/Customers/Index.cshtml
@model IEnumerable<QLKhachSan.Models.Customer>

@{
    ViewBag.Title = "Index";
}

<h2 style="padding-bottom: 20px">Customers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Add)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerType.Name)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CMND)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Add)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerType.Name)
        </td>
    </tr>
}

</table>